version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app.ci
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress.ci
    depends_on:
      - app
    environment:
      - CYPRESS_BASEURL=http://app:3000
